# Site settings
<<<<<<< HEAD
title: Billy Meinke
email: 
description: "The personal website of Billy Meinke"
twitter_username: billymeinke
github_username: billymeinke
baseurl: "/billymeinke.github.io"
=======
title: Your awesome title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
twitter_username: jekyllrb
github_username:  jekyll
baseurl: ""
>>>>>>> FETCH_HEAD

# Build settings
markdown: kramdown
permalink: pretty