# Site settings
title: Billy Meinke
url: http://www.billymeinke.com
description: "The personal website and blog of Billy Meinke"
twitter_username: billymeinke
github_username: billymeinke
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty